# Generated by Django 5.2 on 2025-04-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
